// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdruT1Bo0_A9NWAzc_sh8VwGpWTr8AJcM',
    appId: '1:921914922646:web:bc25adfb9df9df7d2354b7',
    messagingSenderId: '921914922646',
    projectId: 'sisapraukk',
    authDomain: 'sisapraukk.firebaseapp.com',
    storageBucket: 'sisapraukk.firebasestorage.app',
    measurementId: 'G-WB7NLQK043',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWE7tQGUuzvHDD5E1PAyrpVT1hq3ftT2Y',
    appId: '1:921914922646:android:14c3d50409fd7eae2354b7',
    messagingSenderId: '921914922646',
    projectId: 'sisapraukk',
    storageBucket: 'sisapraukk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCquq__BHp0vvMgKQB5lNJi1bqhm2nrZQo',
    appId: '1:921914922646:ios:77e8969dd98ff21b2354b7',
    messagingSenderId: '921914922646',
    projectId: 'sisapraukk',
    storageBucket: 'sisapraukk.firebasestorage.app',
    iosBundleId: 'com.example.sisapraUkk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCquq__BHp0vvMgKQB5lNJi1bqhm2nrZQo',
    appId: '1:921914922646:ios:77e8969dd98ff21b2354b7',
    messagingSenderId: '921914922646',
    projectId: 'sisapraukk',
    storageBucket: 'sisapraukk.firebasestorage.app',
    iosBundleId: 'com.example.sisapraUkk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdruT1Bo0_A9NWAzc_sh8VwGpWTr8AJcM',
    appId: '1:921914922646:web:aaecfc0c286b8d802354b7',
    messagingSenderId: '921914922646',
    projectId: 'sisapraukk',
    authDomain: 'sisapraukk.firebaseapp.com',
    storageBucket: 'sisapraukk.firebasestorage.app',
    measurementId: 'G-SDPLSGD0Y7',
  );
}
